### ISSUE TITLE
Navigation to internal pages with dots in the URL fails on extension detection

### ISSUE THREAD

**Issue by timvdalen** [turbolinks/turbolinks#528] opened 2020-03-11 12:10 UTC
**Describe the bug**
Navigation to internal pages with dots in the URL fails because the location is not visitable (`Controller.locationIsVisitable`).
I suspect this is caused by the definition of `Location.isHTML`.

**To Reproduce**

1. Have an app with a route that allows dots
2. Click a link to or call `Turbolinks.visit('/websites/example.com')`
3. A full page reload (`window.location.href`) happens

**Expected behavior**
Turbolinks navigates to the given location.

**Details (please complete the following information):**
 - Operating System: Windows 10
 - Browser: Chrome
 - Turbolinks 5.2.0

**Additional context**

In `Controller.locationIsVisitable` (https://github.com/turbolinks/turbolinks/blob/271c581/src/controller.ts#L326-L328), the first conditional evaluates to true, since the location is prefixed by the root.
However, the second condition (which I think is there to handle file download links) evaluates to false.
`Location.isHTML` (https://github.com/turbolinks/turbolinks/blob/master/src/location.ts#L57-L59) checks that, if there is a file extension`, it's on a whitelist.
Since the 'extension' of the location is not on the whitelist, it's not visitable.

I don't have a good suggestion for how to solve this issue, as I understand why the current behaviour is the way it is.
Would it make sense to have a global and/or link-level opt-out for the `isHTML` check?

**Comment by domchristie** [comment] 2020-03-11 19:51
Hey @timvdalen,

https://github.com/turbolinks/turbolinks/issues/301 discusses this. The current guidance is to customise `Turbolinks.Location.prototype.isHTML` to suit your needs.

Closing as duplicate of #301

**Closed by domchristie** 2020-03-11 19:51 UTC
Labels: bug

**Comment by timvdalen** [comment] 2020-03-12 09:14
Thanks, I missed that one in my search!
