### ISSUE TITLE
Error Running Turbolinks iOS Demo

### ISSUE THREAD

**Issue by Mardiniii** [turbolinks/turbolinks#183] opened 2016-09-26 14:50 UTC
Hi Everybody!

I saw the talk from @sstephenson about Turbolinks 5. Now, I want to try some exercises before implementing this feature in my work. I want to be clear that I never have used X-Code, I clone this repository https://github.com/turbolinks/turbolinks-ios/ and I was trying to run the demo. I started the server with the Turbolinks 5 app but when I want to run the simulator X-Code is raising the next error and I don't know how to fix it. You can see the error on the next screenshot:

![image](https://cloud.githubusercontent.com/assets/8250324/18838854/7d9c99c6-83ce-11e6-83f3-d27b21cfb91e.png)

 Can you help me please?

**Comment by joemasilotti** [comment] 2016-09-30 14:41
This looks like the same issue as [#68](https://github.com/turbolinks/turbolinks-ios/issues/68) in the iOS project.

**Comment by domchristie** [comment] 2018-09-13 07:35
Closing as duplicate of https://github.com/turbolinks/turbolinks-ios/issues/68

**Closed by domchristie** 2018-09-13 07:35 UTC
