### ISSUE TITLE
Inline script tags evaluated twice

### ISSUE THREAD

**Issue by frenkel** [turbolinks/turbolinks#116] opened 2016-06-16 09:16 UTC
We're having issues with inline script tags being evaluated twice. I've created a simple application to demonstrate the problem at: https://github.com/frenkel/turbolinks-duplicate-script-eval

Steps to reproduce:

1. When you start the application you visit the root page which does not include the script tag.
2. Click the 'Show' link.
3. One console.log is executed.
4. Click the 'Index' link.
5. Click the 'Show' link.
6. Two console.logs are executed.
7. Click the 'Index' link.
8. Click the 'Show' link.
9. Two console.logs are executed.

Please let me know if there is any way for me to help you resolve this bug.

**Comment by liuzhenangel** [comment] 2016-06-17 15:05
@frenkel No, it's not a bug for turbolinks, because turbolinks will load screenshot page before load new page from remote server.

In other word, turbolinks will execute twice script in body when it already has a cache page. You can simplely close this feature with a no-cache meta at this page( see this on README )

**Comment by sstephenson** [comment] 2016-06-20 18:46
@liuzhenangel is correct—this is Turbolinks’ preview cache in action. Please carefully review [Understanding Caching](https://github.com/turbolinks/turbolinks#understanding-caching) from the documentation, and consider responding to Turbolinks’ navigation events instead of using inline script tags.

**Closed by sstephenson** 2016-06-20 18:46 UTC
