### ISSUE TITLE
Media Queries in <body> do not load properly in IE11

### ISSUE THREAD

**Issue by Fudoshiki** [turbolinks/turbolinks#341] opened 2017-12-28 16:42 UTC
Same as https://github.com/turbolinks/turbolinks-classic/issues/568

**Comment by domchristie** [comment] 2018-09-21 09:34
I'm afraid I can't reproduce this on IE11 / Windows 10.

The test case included the following in the `<body>` of a page transitioned to via Turbolinks:

```html
    <style>
      @media(min-width: 800px) {
        h1 {
          background-color: red;
          color: white
        }
      }
    </style>
    <h1>
      Foo
    </h1>
    <form action="/" method="post">
      <input type=submit>
    </form>
```

And the output was as expected, even when resizing. Perhaps it has been fixed in a recent IE update?

Closing this issue for now, but if you can create a live example demonstrating the problem, then please post it here. Thanks!

**Closed by domchristie** 2018-09-21 09:34 UTC
