### ISSUE TITLE
How to clear the turbolinks cache reliably on loading a specific page

### ISSUE THREAD

**Issue by benreyn** [turbolinks/turbolinks#522] opened 2020-02-19 19:22 UTC
I have a specific page that I want to have a fresh turbolinks cachen when the page loads. The first stab at an implementation looked something like this...

```js
$(document).one("turbolinks:load", () =>  {
  Turbolinks.clearCache();
})
```

I was getting some inconsistent results with this method so in an effort to debug I added....

```js
$(document).one("turbolinks:load", () =>  {
  console.log(Turbolinks.controller.cache);
  Turbolinks.clearCache();
  console.log(Turbolinks.controller.cache);
})
```

I soon learned that the first time I logged the cache, I would have the full cache of the Turbolinks session, and after calling `Turbolinks.clearCache()` I would have a cache that contained only the last page before loading the current page. This lead me to discover https://github.com/turbolinks/turbolinks/pull/390 which introduced the idea of defering snapshot caching. My hunch is that _sometimes_ the snapshot is being cached AFTER Ive cleared the cache. What is the recommended way to clear the cache on a page load?

**Comment by DylanReile** [comment] 2020-02-20 01:40
To add more context to our problem, we have a log out form that posts to the #destroy action on our sessions controller. This action  tears down the session, then `redirect_to`s the user to the sessions/new page.

Our problem is that the user can use the browser back button to navigate to cached versions of previous pages, which my contain PPI. This is problematic on a public computer.

This bit of the documentation seems to align perfectly with our use case:
`If form submission results in a state change on the server that affects cached pages, consider clearing Turbolinks’ cache with Turbolinks.clearCache().` 

But, as described calling it on `turbolinks:load` still results in the _last_ page being cached. Is there a different lifecycle event we could hook into to ensure we also clear cache after all caching is finished?

Additionally, one solution our team has found is to add `- set_meta_tags "turbolinks-visit-control" => "reload"` to our sessions/new view. I would love to know why this works. Why should hard reloading the next page clear the cache?

**Comment by domchristie** [comment] 2020-02-21 17:59
Hi @benreyn and @DylanReile

I've not been able to reproduce this, either by clearing the cache on a specific page, or by simulating a log out via a `DELETE` request (see [demo](https://hidden-ocean-93903.herokuapp.com/)).

@DylanReile are you using turbolinks-rails? If so, it should automatically clear the cache before visiting the redirect path, as long as your log out request is not a `GET`.
Regarding `turbolinks-visit-control`: the Turbolinks cache is simply stored as a property on the Turbolinks controller; it's not persisted, so hard reload wipes this out and starts Turbolinks with an empty cache.

@benreyn are you able to reliably reproduce this behaviour? I've tried a few things, including caching heavy pages, but the cache was fully cleared each time 😕 If you can reproduce this with a minimal example, that might help.

Thanks

**Comment by DylanReile** [comment] 2020-02-21 21:55
@domchristie We are using the Turbolinks Rails engine, but our log out request is actually a `GET` for compatibility with our mobile apps. Can you point me to the code with the automatic clearing functionality you mentioned?

**Comment by domchristie** [comment] 2020-02-21 22:40
> Can you point me to the code that's supposed to do that?

In [`Turbolinks::Redirection`](https://github.com/turbolinks/turbolinks-rails/blob/master/lib/turbolinks/redirection.rb), [`redirect_to`](https://github.com/turbolinks/turbolinks-rails/blob/4fffc808b437936808f0888a87b1a1ae1bbcb1cd/lib/turbolinks/redirection.rb#L9-L21) is patched. If the request is an XHR and it's not a `GET`, it will render [JavaScript that clears the cache and visits the `redirect_to` location](https://github.com/turbolinks/turbolinks-rails/blob/4fffc808b437936808f0888a87b1a1ae1bbcb1cd/lib/turbolinks/redirection.rb#L24-L37).

You could emulate this in your case by rendering the JS to clear the cache and visit `sessions/new`:

```js
// sessions/destroy.js.erb
Turbolinks.clearCache()
Turbolinks.visit('/sessions/new', { action: 'replace' })
```

(This assumes that your log out link has the `data-remote="true"` set.)

**Comment by domchristie** [comment] 2020-02-22 00:22
After a bit more digging, I can see that the turbolinks-rails `redirect_to` patch will clear the cache, but because `Turbolinks.visit` is called immediately afterwards, the location it's called from will be in the cache for the subsequent visit. e.g.

1. Click "Log out" from `/home`
2. `DELETE` to `/sessions/destroy` and session is destroyed
3. Turbolinks cache is cleared, and `/sessions/new` is visited
4. `Turbolinks.controller.cache` will include an entry for `/home`

However, because the cache was cleared, _and_ that the visit `action` was `replace`, pressing back should not render a page from the Turbolinks cache.

To fully remove previous cache entries, calling `Turbolinks.clearCache()` when `sessions/new` loads _should_ to the job.

**Comment by DylanReile** [comment] 2020-02-29 01:44
@domchristie Thank you for looking into this. I've created an example app that reproduces the issue: https://github.com/DylanReile/turbolinks_cache

Build it locally and run through these steps:
1. Click "log in". You can see "You're logged in as Dylan".
2. Click "log out".  The sessions/new view is rendered with `Turbolinks.clearCache` and you can see the "turbolinks clear cache fired" was logged in the console.
3. Click the back button in the browser. You can still see "You're logged in as Dylan" despite the cache being cleared!

![cache-issue](https://user-images.githubusercontent.com/10473395/75598608-e6d83000-5a51-11ea-9c2d-43a9c11c8847.gif)

**Comment by domchristie** [comment] 2020-03-02 20:29
@DylanReile thanks for the example, it really helps!

As your log in/out buttons are not using Ajax, the transitions are full page loads; Turbolinks is not involved in the caching or rendering. (You can test this by removing Turbolinks from your application.js pack and observe the same behaviour.) So I think you're seeing the browser's caching and history navigation behaviour. With full page loads, here is what the browser's history stack looks like after each step:

| Step | Action           | Browser history stack        |
| :--- | :--------------- | ---------------------------: |
| 1.   | Navigate to root | `[/]`                        |
| 2.   | Log in           | `[/, /homes]`                |
| 3.   | Log out          | `[/, /homes, /sessions/new]` |
| 4.   | Navigate back    | `[/, /homes]`                |


Turbolinks, with turbolinks-rails and rails-ujs can help fix this :) Change your log out button to a remote one:

```js
<%= button_to 'log out', '/logout', method: :delete, remote: true %>
```

The turbolinks-rails `redirect_to` patch will clear the Turbolinks cache and handle the redirection by replacing the history entry. The browser's history stack will look something like:

| Step | Action                                | Browser history stack        |
| :--- | :------------------------------------ | ---------------------------: |
| 1.   | Navigate to root                      | `[/]`                        |
| 2.   | Log in                                | `[/, /homes]`                |
| 3.   | Log out (Turbolinks replace redirect) | `[/, /sessions/new]`         |
| 4.   | Navigate back                         | `[/]`                        |

Note how the authenticated `/homes` entry gets replaced by the redirected path. What's more, because the Turbolinks cache is cleared, any restoration visit to a page requiring authentication will request a fresh copy from the server (which will probably require re-authentication).

If you are concerned about exposing sensitive personal information after log out, you may also wish to firm this up by considering setting `"no-cache, no-store"` `Cache-Control` response headers on authenticated pages.

I hope that helps! I'll close issue for now, but if you come across further problems, feel free to reply.

**Closed by domchristie** 2020-03-02 20:29 UTC
Labels: question

**Comment by DylanReile** [comment] 2020-03-03 22:27
@domchristie Thanks for the great explanation. Adding `remote: true` does cause Turbolinks to take over the History API, which solves the issue. 

@benreyn TL;DL we were seeing the native browser caching behavior.

Unfortunately we have to use `method: :get` instead of `:delete` due to a limitation of our mobile apps. This causes Turbolinks not to issue a `visit` automatically, which results in the browser not changing pages. I suppose we could have the controller respond with our own SJR that calls `visit`, but for now we'll probably keep the `"turbolinks-visit-control" => "reload"` hack.
