### ISSUE TITLE
Show progressbar on change state (not only loading page url)

### ISSUE THREAD

**Issue by matheusdsm** [turbolinks/turbolinks#136] opened 2016-07-09 04:57 UTC
I need to show progress bar in any user action,
the progress bar is only showing when user go 
to a page.
I wanna know, how to make progress bar show when changing state.

Thanks :)

**Comment by CyberianIce** [comment] 2016-07-25 12:09
[nProgress](https://github.com/rstacruz/nprogress) is simple, free, opensource plugin, compatible with TurboLinks. It is designed exactly for this purpose and easily configurable and customizable.

Have fun!

**Comment by sstephenson** [comment] 2016-07-31 15:21
Duplicate of #93 (rationale: https://github.com/turbolinks/turbolinks/issues/93#issuecomment-221897734).

**Closed by sstephenson** 2016-07-31 15:21 UTC
