### ISSUE TITLE
<script> elements in a page’s <body> will be  evaluated twice.

### ISSUE THREAD

**Issue by wildchildEric** [turbolinks/turbolinks#167] opened 2016-08-16 01:36 UTC
To reproduce this: 
1. add `<script>console.log('hi')</script>` at the end of a page <body>,
2.reload the page, 'hi' will be printed once
3., go to another page and then go back, 'hi' will be printed twice.

After disable the cache(add `<meta name="turbolinks-cache-control" content="no-cache">`),
this behavior disappears.

**Comment by rushingfitness** [comment] 2016-08-17 13:31
I noticed a similar issue when I upgraded to version 5. I dropped it back down to what I used to use (2.5.3) and it works fine again. So something has definitely changed as far as how js is being handled.

**Comment by rushingfitness** [comment] 2016-08-17 13:35
Perhaps this block of text from the README could help you?

    Turbolinks evaluates <script> elements in a page’s <body> each time it renders the
    page. You can use inline body scripts to set up per-page JavaScript state or bootstrap
    client-side models. To install behavior, or to perform more complex operations when
    the page changes, avoid script elements and use the turbolinks:load event instead.

    Annotate <script> elements with data-turbolinks-eval="false" if you do not want
    Turbolinks to evaluate them after rendering. Note that this annotation will not prevent
    your browser from evaluating scripts on the initial page load.

**Comment by lifeiscontent** [comment] 2016-09-14 00:34
@rushingfitness so I've spent a bit of time playing with this, if I put a variable in my head tag called `x` and increment it in the body, sometimes it updates twice on a single render.

**Comment by mystdeim** [comment] 2016-11-05 15:22
I have the same issue. It seems a bug with a cache

**Comment by bennacer860** [comment] 2017-01-18 21:47
I am having a similar issue and annotating the <script> elements with data-turbolinks-eval="false" is not doing anything.

**Comment by nateberkopec** [comment] 2017-01-19 14:50
> if I put a variable in my head tag called x and increment it in the body, sometimes it updates twice on a single render.

Everyone in this issue that's "seeing something evaluated twice" is seeing the preview feature at work. Since previews depend on the cache, disabling the cache seems to "fix" the behavior, but you could also just disable previews by adding `<meta name="turbolinks-cache-control" content="no-preview">` or by [doing something when a preview is being displayed.](https://github.com/turbolinks/turbolinks#detecting-when-a-preview-is-visible)

This is all expected behavior - Turbolinks expects all scripts on a page to be idempotent. Incrementing a variable would not be idempotent.

**Comment by diegoacuna** [comment] 2017-07-06 21:00
> This is all expected behavior - Turbolinks expects all scripts on a page to be idempotent. Incrementing a variable would not be idempotent.

@nateberkopec this doesn't explain the original issue posted by @wildchildEric right?

**Comment by nateberkopec** [comment] 2017-07-06 21:36
Logging something to the console isn't an idempotent operation, so no.

Your Javascript may be executed twice on any given page load when using Turbolinks. You can either make your Javascript idempotent, or turn off previews.

**Comment by domchristie** [comment] 2018-09-14 17:13
Closing as resolved by https://github.com/turbolinks/turbolinks/issues/167#issuecomment-273795538 and https://github.com/turbolinks/turbolinks/issues/167#issuecomment-313526256

**Closed by domchristie** 2018-09-14 17:13 UTC
