### ISSUE TITLE
NPM: TypeError: this is undefined

### ISSUE THREAD

**Issue by jpic** [turbolinks/turbolinks#379] opened 2018-04-12 17:32 UTC
When loading turbolinks with npm, as such:

```
var Turbolinks = require('turbolinks')
Turbolinks.start()
```

It raises exception:

```
TypeError: this is undefined
```

I found the following workaround:

```
(() => {
  var Turbolinks = require('turbolinks')
  Turbolinks.start()
}).bind(window)()
```

Should we document it, or try to find the underlying issue ?

**Comment by javan** [comment] 2018-04-12 17:49
What version of Turbolinks do you have? That looks similar to #352 in v5.1.0, which was fixed in v.5.1.1.

Or, maybe you have `node_modules/` passing through babel-loader? See https://twitter.com/javan/status/952567867026952192

**Comment by jpic** [comment] 2018-04-12 18:06
It's [excluded from babel-loader](https://github.com/yourlabs/crudlfap/blob/master/webpack.config.js#L29), because otherwise it just didn't work at all.

We [have 5.1.1](https://github.com/yourlabs/crudlfap/blob/master/package.json#L34).

**Comment by javan** [comment] 2018-04-13 13:33
Hmm, I can't reproduce. Here's what I tried:

Source → https://glitch.com/edit/#!/hello-turbolinks?path=src/index.js:4:50
Demo → https://hello-turbolinks.glitch.me/

**Closed** 2018-09-18 08:01 UTC
