### ISSUE TITLE
XHR error with http 0

### ISSUE THREAD

**Issue by PierBover** [turbolinks/turbolinks#423] opened 2018-10-04 01:57 UTC
This is pretty weird. When enabling Turbolinks, some of my XHR requests are failing.

I don't get an error event, but the HTTP response code is `0` and the `responseText` is empty.

My XHR code is pretty simple:
```js
var postsRequest = new XMLHttpRequest();

postsRequest.onload = function () {
	// do stuff...
}

document.addEventListener("turbolinks:load", function() {
	postsRequest.open('GET', 'https://...');
	postsRequest.send();
});
```

The script tag is somewhere in the body.

On first load everything works fine, but when changing to a new a page the problem appears. If I disable Turbolinks everything goes back to normal. I've tried both Chrome and Firefox with the same result.

Console in Chrome:
![image](https://user-images.githubusercontent.com/226483/46448892-c61d8500-c74e-11e8-8232-c1a9b0cab518.png)

Console in Firefox:
![image](https://user-images.githubusercontent.com/226483/46448901-e1889000-c74e-11e8-9144-65ae8aebf18a.png)

As you can see, the first request is fine, but the second exhibits the problem.

Am I missing something very obvious here?

**Comment by domchristie** [comment] 2018-11-02 10:55
I've not been able to reproduce this. Can you think of anything else you might be doing on `turbolinks:load` which might be affecting this? If you could post a minimal demonstration of the problem, that might help.

**Comment by PierBover** [comment] 2018-11-02 14:05
Hey @domchristie I'll try to create a repro in a couple of days.

**Comment by domchristie** [comment] 2018-11-16 08:35
Hey @PierBover, I'll close this issue for now, but feel free to reopen if you get a chance to create the demo.

**Closed by domchristie** 2018-11-16 08:35 UTC

**Comment by domchristie** [comment] 2018-11-16 18:49
> I hope this is helpful.

**Massively**! 🎉 Hopefully I can clarify what's going on in each step.

> When you get to Page 2 an XHR request should have been triggered on turbolinks:load but nothing happens.

This is because `turbolinks:load` has already been triggered—before `test.js` is evaluated…

When a page is loaded via Turbolinks, it does not wait for external scripts in the body to be evaluated before triggering `turbolinks:load`, so what you are seeing is:

1. HTML is loaded via XHR
2. `<head>` is merged and `<body>` is replaced
3. `turbolinks:load` is triggered
4. `test.js` is downloaded and evaluated

You will see the expected behaviour if you reload page 2 fully. This is because the following happens:

1. HTML is loaded and parsed (including `test.js` evaluation)
2. `DOMContentLoaded` is triggered
3. `turbolinks:load` is triggered

> Click on the link to go back to Page 1. Now the XHR triggers, although the JavaScript file was included on Page 2, not on Page 1.

This happens because the XHR is sent in a `turbolinks:load` event handler which is then executed on every subsequent page load:

1. Page 2 is visited
2. XHR set up to be sent on `turbolinks:load`
3. Page 1 visited—`turbolinks:load` triggered
4. XHR sent

Unlike with "traditional" page loads, in Turbolinks apps, event listeners are not torn down when navigating between pages. So even though `test.js` is only included on page 2, because it sets up an event handler to run on `turbolinks:load`, this handler is called on every subsequent `turbolinks:load` event. What's more, if you revisit page 2, the XHR will be sent (on `turbolinks:load`) _and_ it will set up _another_ handler which does the same thing—so you get duplicate events 😬

Traditionally inline/page-specific scripts are often interpreted as "scripts that are only run on this page". However, if they include event listeners that are not removed, this won't be the case and can lead to some confusion. For these reasons, as a general rule, I'd avoid adding event listeners in inline body scripts.

> Go back to Page 2, and now the XHR triggers with the HTTP status code 0 I was mentioning above.

I have a vague idea of what might be happening here, although I'm having a little trouble getting my head around it. I think this is what's happening:

1. Page 1 visited
2. Page 2 visited (`turbolinks:load` is triggered)
3. `test.js` is loaded and the XHR `request` is scheduled to be sent on `turbolinks:load`
4. Page 1 visited (`turbolinks:load` is triggered)
5. `request` is sent as was scheduled in step 3 (status `200`)
6. Page 2 visited (`turbolinks:load` is triggered)
7. `request` is sent…
8. `test.js` is loaded and the XHR `request` is overwritten/cancelled (status `0`) and then is scheduled (again) to be sent on `turbolinks:load`

Here is a runnable demonstration of that:

```js
// Global variable
var request

function setup () {
  request = new XMLHttpRequest();
  
  request.onload = function () {
    console.log('XHR onload');
    try {
      console.log('HTTP code:', request.status);
    } catch (error) {
      console.log(error);
    }
  }
}

function send () {
  request.open('GET', 'https://jsonplaceholder.typicode.com/todos');
  request.send();
}

// Initial visit just sets up the XHR. It's not sent until next page load.
function initialVisit () {
  setup()
}

// The XHR is sent, but then immediately setup again, overwriting `request`
function subsequentVisit () {
  send()
  setup()
}

initialVisit()
subsequentVisit()
```

I _think_ that because `request` is immediately overwritten after being sent, this effectively cancels the XHR, and therefore the status is `0`.

---

With all of the above in mind, if you just want to fetch some data when a page loads, the simplest modification to your code would be to remove the `turbolinks:load` event listener, and just call `request.open` and `request.send` after the set up. You should also wrap the whole script in an IIFE, to prevent polluting the global scope, so something like:

```js
;(function () {
  var request = new XMLHttpRequest();

  request.onload = function () {
    console.log('XHR onload');
    try {
      console.log('HTTP code:', request.status);
      var element = document.getElementById('status');
      element.textContent = 'XHR Loaded!'
    } catch (error) {
      console.log(error);
    }
  }

  request.ontimeout = function (event) {
    console.log('XHR ontimedout', event);
  };

  request.onerror = function (event) {
    console.log('XHR onerror', event);
  };

  request.open('GET', 'https://jsonplaceholder.typicode.com/todos');
  request.send();
})();
```

I hope that helps!

**Comment by PierBover** [comment] 2018-11-16 20:41
Oh wow, thanks for taking the time explain this with such detail!

It's safe to say this has been pretty well documented for posterity.

**Comment by domchristie** [comment] 2018-11-16 21:15
Glad to help, and hope it makes sense!
