### ISSUE TITLE
Rails 5 respond_to (format.xml) unexpected behaviour

### ISSUE THREAD

**Issue by petermumford** [turbolinks/turbolinks#40] opened 2016-03-08 14:03 UTC
When using a **respond_to** block and if you have a `format.xml` it will always use this no matter what else you have even if you're expecting a `html` response. Please look at this issue on rails rails/rails#24035 to get a full description of the issue.

**Comment by packagethief** [comment] 2016-03-08 16:12
Thanks @petermumford. Confirmed. This is likely because [we set the Accept header to include "application/xml"](https://github.com/turbolinks/turbolinks/blob/master/src/turbolinks/http_request.coffee#L66). This seems unnecessary and can be removed.

I'll open a PR to remove it later unless someone beats me to it.

**Comment by packagethief** [comment] 2016-03-09 06:05
Fixed by removing "application/xml" from the Accept header in #41

**Closed by packagethief** 2016-03-09 06:05 UTC
