### ISSUE TITLE
Root element (<html>) attributes not merged

### ISSUE THREAD

**Issue by wc-matteo** [turbolinks/turbolinks#372] opened 2018-03-22 09:46 UTC
For example a css class on `<html>` that changes every page, doesn't get updated.

**Comment by stevenpetryk** [comment] 2018-04-03 20:24
Turbolinks only merges `<head>` and swaps out `<body>`. This is intended behavior. It should be easy enough to move your class from `<html>` to `<body>`.

**Comment by stevenpetryk** [comment] 2018-04-04 17:57
There's a chance that it's because adding `class` to HTML wasn't allowed by the specification until HTML5 came out, but personally I have no idea. I think it might be useful.

**Comment by wc-matteo** [comment] 2018-04-05 07:10
I don't think that `class` on `html` wasn't allowed before HTML5 and it's not something so uncommon: see [modernizr](https://modernizr.com/), for instance.

**Comment by domchristie** [comment] 2018-09-14 09:26
This is not straightforward because it's not clear how HTML attributes should be handled—should their contents be replaced, or should they be merged?

For example, let's say we add class names to denote the page controller/action:

```html
<html class="posts posts-index">
```

We can then scope our styles depending on the context. But what should happen when we visit `posts#show` which sends over:

```html
<html class="posts posts-show">
```

Should the class name be replaced: `class="posts posts-show"`, or should the contents be merged: `class="posts posts-index posts-show"`? If we are using the class to scope styles, then we probably want them replaced otherwise our class attribute could eventually end up with _all_ the classes for our entire app :/ However if we replace the contents, we face a different problem…

Modernizr dynamically adds class names to the HTML on the initial page load e.g. `class="js no-touch svg"`. When a new page is loaded, the HTML class attributes in the response won't include any of these dynamically added classes, so if the class contents are _replaced_, the Modernizr class names will be removed and dependent code will break :/

So unfortunately there isn't an easy solution to this problem 😞 If you control the code which generates your HTML, then you _could_ add a data attribute on the `body` element containing all the HTML attributes e.g. (`data-html-attributes="{\"attribute\": \"value\"}"`), and then apply them on `turbolinks:load`. If you don't have that control then you may want to look into [`turbolinks:request-end`](https://github.com/turbolinks/turbolinks#full-list-of-events), which includes the response HTML in `event.data.xhr.response`. Theoretically you could parse this get the HTML attributes and as before, apply them on `turbolinks:load`. It might be worth a try, or it might get messy!

**Closed by domchristie** 2018-09-14 09:26 UTC

**Comment by wc-matteo** [comment] 2018-09-14 09:36
I think it is pretty clear, unless I'm missing something...

The solution would be to replace all attributes with those sent by the server and then let the other scripts (like modernizr) run.

Modernizr should run for every page even when using turbolinks, right?

**Comment by domchristie** [comment] 2018-09-14 09:48
>  The solution would be to replace all attributes with those sent by the server and then let the other scripts (like modernizr) run.
>
> Modernizr should run for every page even when using turbolinks, right?

To achieve the performance benefits, scripts are parsed and evaluated just once. So Modernizr only adds classes on the initial page load.
