### ISSUE TITLE
Filling body damages browser extensions

### ISSUE THREAD

**Issue by Sunhat** [turbolinks/turbolinks#393] opened 2018-06-14 09:32 UTC
Hi, targeting the `<body>` for full dom replacement is extremely bad practice.

Switch this out for a `<div id="app"></div>`

Thanks

**Comment by absolux** [comment] 2018-08-08 17:44
Hello @Sunhat, Can you give us more info how it damages the browser extensions ?

I've found another issue #400 where replacing the whole `body` tag prevent ad trackers to work correctly. There is also a pull request #401 to set a root element instead of the awesome `body`

**Comment by MidnightWonderer** [comment] 2018-08-30 04:07
Hello @absolux  
It is not so uncommon for a browser extension to append elements to `<body>`.  
For instance when they want to show something to the user on the page.
  
If you swap out the entire body. The appended elements will be gone, along with the body.

**Comment by kmmbvnr** [comment] 2018-08-30 04:34
Body element swapping also cause problems with web component custom elements polyfill - https://github.com/webcomponents/custom-elements/pull/134

**Comment by domchristie** [comment] 2018-09-28 11:08
Closing as a duplicate of https://github.com/turbolinks/turbolinks/issues/43.

**Closed by domchristie** 2018-09-28 11:08 UTC
