### ISSUE TITLE
Support Turbolinks.visit(path, { action: 'inject' })

### ISSUE THREAD

**Issue by bholtbholt** [turbolinks/turbolinks#563] opened 2020-07-13 15:51 UTC
**Is your feature request related to a problem? Please describe.**
We use Turbolinks with Bootstrap for UI. [Bootstrap Tabs](https://getbootstrap.com/docs/4.5/components/navs/#tabs) is a common pattern throughout the app, which loads all of the HTML within separate divs and shows/hides only the selected tab. We've enhanced this to update the address bar so if someone switches tabs then hard-refreshes, the last tab will be selected.

Moving forward is history is no problem, but because we're injecting history states `history.replaceState(newPath, document.title, newPath);`, we're noticing bugs in back behaviour. Turbolinks doesn't appear to have any knowledge of our changed history. We need to reach into Turbolinks internals to add it:

```javascript
Turbolinks.controller.replaceHistoryWithLocationAndRestorationIdentifier(location.href, uuid());
```

**Describe the solution you'd like**
It would be nice if either:
- Turbolinks listened for history state mutations automatically
- Or if we could inject history into Turbolinks

Instead of our code looking like:
```javascript
  function updateNavigation(e) {
    var newTab, newPath;
    // Drop # from the href attribute
    newTab = e.target.getAttribute('href').substring(1);
    // Create a new location.search with tab params
    newPath = replaceQueryParam('tab', newTab, location.search);
    // Replace the current history state so back doesn't get stuck
    // in tabs on desktop or cause issues in mobile
    history.replaceState(newPath, document.title, newPath);
  }
```
It could look like:
```javascript
  function updateNavigation(e) {
    var newTab, newPath;
    // Drop # from the href attribute
    newTab = e.target.getAttribute('href').substring(1);
    // Create a new location.search with tab params
    newPath = replaceQueryParam('tab', newTab, location.search);
    // Replace the current history state so back doesn't get stuck
    // in tabs on desktop or cause issues in mobile
   Turbolinks.visit(newPath, { action: 'inject' });
  }
```

This **wouldn't** cause the page to re-render. It would just add a history state that Turbolinks was aware of.

**Describe alternatives you've considered**
- A regular Turbolinks visit, but we don't want the page to re-render.
- Hooking into Turbolinks internals

**Comment by domchristie** [comment] 2020-09-26 21:51
Hey @bholtbholt, I like the thinking 👍 
I wonder if we should cater for both push and replace states? And given that it won't go through the entire `Visit` lifecycle, perhaps two methods would be preferable than an option? e.g. `Turbolinks.replaceState(…)` and `Turbolinks.pushState(…)`

I'll close this as a duplicate of https://github.com/turbolinks/turbolinks/pull/61
Thanks!

**Closed by domchristie** 2020-09-26 21:51 UTC
Labels: enhancement
