### ISSUE TITLE
Make links go back

### ISSUE THREAD

**Issue by obnijnil** [turbolinks/turbolinks#299] opened 2017-06-04 09:43 UTC
Is there an unobtrusive way of making links go back to the previous location (like `history.back()`), by adding a specific attribute name/value, like

```html
<a href="fallback-url" data-back>Back</a>
<!-- or -->
<a href="fallback-url" class="back">Back</a>
```

I found that there is no **back** option for `data-turbolinks-action` https://github.com/turbolinks/turbolinks#application-visits.

**Comment by sahibalejandro** [comment] 2017-08-30 23:35
This feature could be related to this other topics:

https://github.com/turbolinks/turbolinks/issues/88
https://github.com/turbolinks/turbolinks-ios/issues/81
https://github.com/turbolinks/turbolinks/issues/74

**Comment by domchristie** [comment] 2018-09-13 13:05
Closing as duplicate of #74

**Closed by domchristie** 2018-09-13 13:05 UTC
