### ISSUE TITLE
[Turbolinks Rails 5] anchor element href anchors triggering full-page request

### ISSUE THREAD

**Issue by dansteele** [turbolinks/turbolinks#105] opened 2016-05-25 12:26 UTC
Howdy,

I'm using **Rails 5.0.0rc1**, **turbolinks (5.0.0.beta2)** (gem), and the gem installed **turbolinks-source (5.0.0.beta5)**. Also using jquery-turbolinks, but I have removed this dependency and the issue still happens.

I have narrowed down the problem to turbolinks, or something closely turbolinks related, as the issue no longer occurs when the dependency is removed.

If I have this simple element:
```html
<a href="#">Test</a>
```

When clicked on, this triggers a full-page xhr request. By this I mean it does a normal xhr get as you'd expect Turbolinks to, but the response includes the entire page. `<head>` and all. This causes a lot of weird bugs, as you might expect.

I've managed to solve the isse with the following code:
```javascript
document.addEventListener('turbolinks:before-visit', function(e) {
  if (e.data.url.split(window.location.href)[1].length > 0) {
    e.preventDefault();
    window.location.href = e.data.url;
  }
});
```

This resolved the issue for now, but I'd obviously love to get it working properly. Thanks in advance for any help! Let me know if you need any more info from me

**Comment by dcrec1** [comment] 2016-06-04 17:46
I'm experiencing the same behaviour.

**Comment by packagethief** [comment] 2016-06-13 14:51
Closing as a duplicate of #75

**Closed by packagethief** 2016-06-13 14:51 UTC

**Comment by jendiamond** [comment] 2017-04-06 07:12
I am also experiencing this behaviour.
