### ISSUE TITLE
Guarantee script loading order when mutating `<head>`

### ISSUE THREAD

**Issue by jonleighton** [turbolinks/turbolinks#282] opened 2017-05-03 15:44 UTC
From the docs:

> When you navigate to a new page, Turbolinks looks for any `<script>` elements in the new page’s `<head>` that aren’t present on the current page. Then it appends them to the current `<head>` where they’re loaded and evaluated by the browser. You can use this to load additional JavaScript files on-demand.

Suppose I have a page which renders the following in `<head>` (but assuming these tags aren't rendered on my site's other pages):

``` html
<script src="a.js"></script>
<script src="b.js"></script>
```

When navigating to my page *without* Turbolinks, the browser will guarantee the loading order of the scripts. `a.js` will be executed before `b.js`.

When navigating to my page *with* Turbolinks, the elements will be dynamically inserted into the `<head>`. This means that the loading order will *not* be guaranteed; it may be that `b.js` executes before `a.js`. This causes problems if one is dependent on the other.

Would it be possible for Turbolinks to somehow guarantee the loading order of scripts when it dynamically inserts them into the `<head>`? It's probably not appropriate to literally insert the first script, wait for its `onload`, then insert the second, and so on, since that'll make the request sequential as well.

**Comment by panoply** [comment] 2017-05-11 10:07
I have battled this issue before. 

My solution was to use [Loadjs](https://github.com/muicss/loadjs) which is a poetic async loader / dependency manager and will add only like 740 bytes to your build. This technique for me has become my standard approach in dealing with initialising component dependants. 

Let's say you're ruthless as fuck and your current app depends on GoogleMaps API, Swiper Carousel and jQuery. Now if you're already using Turbolinks, below is how you would use Loadjs to handle this in conjunction with Turbolinks:

Firstly, include Loadjs in `<head>` as per its documentation stipulates. 

```
<script>
    // loadjs here
</script>
```
Lets separate these components into logical chunks, for example Turbolinks, Swiper and Google Maps don't require jQuery, so we load and initialize these separately from one another. 

**Turbolinks**

```
if (!loadjs.isDefined('TURBOLINKS')) {
   loadjs([
      "../turbolinks.js"
   ], 'BUNDLE', {
      before: function(path,  el) {
         switch (path) {
            case "../turbolinks.js":
            el.setAttribute('data-turbolinks-eval', 'false');
         }
      }
   });
}
```

**Google Maps**

```
if (!loadjs.isDefined('MAPS')) {
   loadjs([
      "https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY"
   ], 'MAPS', {
      before: function(path,  el) {
         switch (path) {
            case "https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY":
            el.setAttribute('data-turbolinks-eval', 'false');
         }
      }
   });
}
```

**Swiper Carousel**

```
if (!loadjs.isDefined('SWIPER')) {
   loadjs([
      "../swiper.js"
   ], 'SWIPER', {
      before: function(path,  el) {
         switch (path) {
            case "../swiper.js":
            el.setAttribute('data-turbolinks-eval', 'false');
         }
      }
   });
}
```

**jQuery**

```
if (!loadjs.isDefined('JQUERY')) {
   loadjs([
      "../jquery.js"
   ], 'SWIPER', {
      before: function(path,  el) {
         switch (path) {
            case "../jquery.js":
            el.setAttribute('data-turbolinks-eval', 'false');
         }
      }
   });
}
```

So now, you have multiple components loaded in async. You can also set `async` to **false** with  loadjs and get ordered script loading (as per your question) eg:

```
if (!loadjs.isDefined('COMPONENTS')) {
   loadjs([
      "../turbolinks.js",
      "../swiper.js",
      "../https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY",
      "../jquery.js"
   ], 'COMPONENTS', {
      async:false, // here
      before: function(path,  el) {
         switch (path) {
            case "../turbolinks.js":
            case "../swiper.js":
            case "https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY":
            case "../jquery.js":
            el.setAttribute('data-turbolinks-eval', 'false');
         }
      }
   });
}
```
What you have now is a bunch of dependencies and you can just call your function initializes as follows:

```
loadjs.ready(['TURBOLINKS'], {
   success: function() {  Turbolinks.start();  }
});
loadjs.ready(['JQUERY'], {
   success: function() {  //  }
});
loadjs.ready(['SWIPER'], {
   success: function() {  //  }
});
loadjs.ready(['MAPS'], {
   success: function() {  //  }
});

```
or per by the group bundle:

```
loadjs.ready(['COMPONENTS'], {
   success: function() {  //  }
});

```

or by all:

```
loadjs.ready(['TURBOLINKS','JQUERY','SWIPER','MAPS'], {
   success: function() {  
     Turbolinks.start();
    // others
  }
});
```

I hope this helps.

**Comment by kmmbvnr** [comment] 2018-01-06 08:13
I looked how loadjs `async=false` works and actually it just inserts script tag into head with `async=false` attribute.  All modern browsers would load scripts async, but evaluate them in the declared order.

https://developer.mozilla.org/ru/docs/Web/HTML/Element/script

https://wiki.whatwg.org/wiki/Dynamic_Script_Execution_Order

Turbolinks perform script tag clone, so to get sync load behavior you just need to declare script with explicit `async=false` and it would be closed by turbolinks.

**Comment by javan** [comment] 2018-01-08 14:53
Thank you, @kmmbvnr! I assumed that `async = false` was essentially a no-op in this context since scripts aren't loaded synchronously. I've applied this change in https://github.com/turbolinks/turbolinks/pull/351 and confirmed that it does indeed ensure the load order.

**Closed** 2018-01-08 14:53 UTC
