### ISSUE TITLE
Bug??! 404page(404 responce status code) and <meta name="turbolinks-visit-control" content="reload">

### ISSUE THREAD

**Issue by kat0d** [turbolinks/turbolinks#466] opened 2019-04-22 08:26 UTC
Try to use ```<meta name="turbolinks-visit-control" content="reload">``` on a 404 page, and it's not work for me, does not reload page.
I had test it on normal pages, and it's work fine on all pages i mean with ```<meta name="turbolinks-visit-control" content="reload">``` pages are reloads. Exept those, with 404 responce code.
Or this is a normal turbolinks behavior(to not use ```turbolinks-visit-control``` metatag on 404 pages) ?
Or it's just me has this bug ?
Using Turbolinks 5.2.0

head html of 404 page 
```html

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<base href="https://site-new/">
	<title>404</title>
	<link rel="stylesheet" href="/min.css" type="text/css" data-turbolinks-track="reload">
	<script src="/_js/vendor.js" defer></script>
	<script src="/_js/main.js" defer></script>
	<meta name="turbolinks-visit-control" content="reload">
</head>
```
and i'm realy using it on local server with https://site-new/ domain

**Comment by tvandervossen** [comment] 2019-04-24 08:21
Yes, this is normal.

Turbolinks handles any HTTP response outside of the 2xx successful range differently. See #179 for more details and some guidance on how you can change this behaviour.

**Comment by kat0d** [comment] 2019-04-24 10:38
> Yes, this is normal.
> Turbolinks handles any HTTP response outside of the 2xx successful range differently. See #179 for more details and some guidance on how you can change this behaviour.

thanks for link. with monkey patch it's ok)

**Comment by domchristie** [comment] 2019-04-25 08:11
Closing as duplicate of #179

**Closed by domchristie** 2019-04-25 08:11 UTC
