### ISSUE TITLE
Safari: Browser prompt for form re-submit

### ISSUE THREAD

**Issue by elsurudo** [turbolinks/turbolinks#257] opened 2017-04-12 13:49 UTC
1. Submit a _non-remote_ form with a validation error. Rails renders "new" action again and we see the form with validation errors
2. Navigate to any other page via a link (turbolinks handles this – no reload)
3. Refresh the page via the browser's refresh button

Expected: page refreshes
Actual: I get a browser prompt asking me if I want to re-submit the form

This is happening in Safari, seems to work as expected in Chrome and FF.

Chrome and FF, however, don't allow me re-submit the form _before I navigate away from the form page_ by clinking "refresh".

May be related to #60

**Comment by victorlcampos** [comment] 2017-05-08 13:04
Yes, the inverce problem occurs with chrome and FF.

1. Submit a non-remote form with a validation error. Rails renders "new" action again and we see the form with validation errors
2. Refresh the page via the browser's refresh button

Expected: Browser prompt asking me if I want to re-submit the form

**Comment by domchristie** [comment] 2018-09-21 07:21
Closing as duplicate of #60. I have added some more detail explaining the complexity in https://github.com/turbolinks/turbolinks/issues/60#issuecomment-423437233

**Closed by domchristie** 2018-09-21 07:21 UTC

**Comment by domchristie** [comment] 2018-11-23 10:01
This appears to be a browser bug with Chrome/Firefox when the history API is used. I have added some more detail in https://github.com/turbolinks/turbolinks/issues/60#issuecomment-441006244
