### ISSUE TITLE
Enable turbolinks for non-GET requests similar to turbolinks-classic

### ISSUE THREAD

**Issue by printercu** [turbolinks/turbolinks#247] opened 2017-03-10 13:46 UTC
Hi!

Is there any reason not to make turbolinks work as in previous versions? From old readme:

```
* `POST :create` => resource successfully created => redirect to `GET :show`
  * Turbolinks **ENABLED**
* `POST :create` => resource creation failed => render `:new`
  * Turbolinks **DISABLED**
```

UPD. For example `devise` would work by default with turbolinks.

**Comment by focused** [comment] 2017-04-20 18:29
Is #251 similar to this issue

**Comment by domchristie** [comment] 2018-09-22 20:51
Closing as duplicate of #60. I have added some more detail explaining the complexity in https://github.com/turbolinks/turbolinks/issues/60#issuecomment-423437233

**Closed by domchristie** 2018-09-22 20:51 UTC
