### ISSUE TITLE
How to hack on Turbolinks

### ISSUE THREAD

**Issue by justin808** [turbolinks/turbolinks#22] opened 2016-02-25 19:06 UTC
I got this feedback on the turbolinks-source gem and and wanted to share it:

From @sstephenson 

Hey Justin,

Easiest way to hack on Turbolinks in a Rails app is to add the src directory to your asset paths in `config/application.rb`:

```ruby
module Foo
  class Application < Rails::Application
    config.assets.paths.unshift("/path/to/turbolinks/src")
    # …
  end
end
```
Make sure you restart the app for the change to take effect.

**Comment by sstephenson** [comment] 2016-02-25 20:38
@justin808, would you like to add this to the wiki, or perhaps open a pull request to add it to the readme?

**Comment by justin808** [comment] 2016-02-26 00:04
Will do @sstephenson! What's the status on being able to get this code from npm? Maybe I or one of my team members can help with this. I'm thinking turbolinks will be a key part of making hybrid Rails + React  apps work that are based on https://github.com/shakacode/react_on_rails/. The npm part is useful as we'd like to have 100% of the JS code in ES6 format, and from npm.

**Comment by justin808** [comment] 2016-03-07 08:20
@sstephenson I found that I can only get this to work when I put this on the layout.

```erb
  <%= javascript_include_tag "turbolinks" %>
```

When I have a 
```js
//= require turbolinks
```

Then I don't get the file loaded.

This is not turbolinks specific, but something to do with sprockets 3.5.x.

Any ideas?

Should I just hack on this with the direct reference on the main layout?

**Comment by packagethief** [comment] 2016-03-08 16:30
Hey Justin. I'm not able to reproduce this on Rails master or 5.0.0.beta3.

**Comment by justin808** [comment] 2016-03-08 18:13
@packagethief I'm hacking on this with Rails 4. In any case, my issue is unrelated to TurboLinks. It's some sort of sprockets issue.

**Comment by packagethief** [comment] 2016-03-08 19:08
Cool, thanks for clarifying. I'll close this issue.

**Closed by packagethief** 2016-03-08 19:08 UTC
