### ISSUE TITLE
Restoration visits needed on mobile web after form submit

### ISSUE THREAD

**Issue by gregblass** [turbolinks/turbolinks#88] opened 2016-05-05 02:16 UTC
Here's my app flow:

1) Index page. Stack is:
`[Index]`

2) User clicks through to a show page. Stack is:
`[Index][Show]`

3) User clicks through to an edit page. Stack is:
`[Index][Show][Edit]`

4) User submits a remote form. Validations pass, Turbolinks does its magic with a redirect_to and the user is back to the show page.

Now here's the issue: the stack is now:
`[Index][Show][Show]`

The user hits the back button and expects to go back to the Index page, but they have to do it twice.

Any ideas of how I could essentially make the stack go backwards (this is what a restore is, right?) after a form submit?

**Comment by gregblass** [comment] 2016-05-05 02:26
Looks like this is the same thing explained here: https://github.com/turbolinks/turbolinks/issues/74

I really think this is a pretty solid issue worth pursuing.

**Comment by gregblass** [comment] 2016-05-07 03:02
Refactoring about 15 forms to load in modals right now, partly because of this. The end experience will be awesome, so its all good - however, in principal, I do really think it is common use case to move backwards down the stack on mobile web in addition to native.

**Comment by nateberkopec** [comment] 2016-05-08 13:54
> The user hits the back button and expects to go back to the Index page

I would expect to go back to the Edit page. That's what would happen if this was a regular, no-Turbolinks app, right? You would click back, ignore the "resubmit form?" box, then press back again and end up at the edit action.

**Comment by gregblass** [comment] 2016-05-08 13:56
I'm not really looking at it like a desktop browser, I'm looking at it like a mobile app - like the chevron left arrow on the Facebook iOS app (or almost any mobile app really. For me I'm replacing the hamburger with back arrows as you move down the stack.

**Comment by nateberkopec** [comment] 2016-05-08 14:03
Ah yes, I read this issue before #74 - I'm not familiar with the mobile use case 👍

**Comment by JonasNielsen** [comment] 2016-07-27 13:32
I'm facing the same issue. @gregblass did you come across any workarounds besides displaying forms in modals?

**Comment by JonasNielsen** [comment] 2016-08-04 08:05
We're quite stuck on this issue. 

Sorry to ping you, but perhaps @sstephenson @packagethief can offer some guidlines? It seems like a very common problem.

I'm happy to put together a demo project if @gregblass explnation of the problem isn't clear enough.

**Comment by sstephenson** [comment] 2016-08-04 15:21
Hey there. I apologize for not doing a better job of responding other than just leaving this issue open in the queue. We’re aware of the problem and are in the planning stages of a more general fix. This is the primary thing we want to address in Turbolinks 5.1.

**Comment by JonasNielsen** [comment] 2016-08-05 07:12
Thanks @sstephenson, really appreciate it! 
Do you have a feeling for a rough time estimate? (i.e. closer to 2 weeks or 2 months?) 
We have a release coming up and I'm trying to decide if we should prioritise rewriting how we handle form submissions.

**Comment by gregblass** [comment] 2016-08-10 01:22
Awesome. While the modals are nice, I have actually be running into some edge case issues with them on different platforms and I'd rather just go back to standard code. Thanks @sstephenson!

**Comment by lucadegasperi** [comment] 2016-10-31 16:09
Any news on this one? I'm stuck with the same problem and would rather have a solid solution than to display forms in modals.

**Comment by elsurudo** [comment] 2016-11-29 13:18
Had the exact same issue – I think this is a really common need and should be built-in, and frankly I expected it would just magically work if I returned JS of `history.back();`

My current workaround is executing `Turbolinks.visit('/turbolinks/back');` in JS, and then capturing it in my iOS app like so:

```
func session(session: Session, didProposeVisitToURL URL: NSURL, withAction action: Action) {
        if URL.path == "/turbolinks/back" {
            popViewControllerAnimated(true)
        } else {
            presentVisitableForSession(session, URL: URL, action: action)
        }
    }
```

And similarly for the Android adapter.

**Comment by lucadegasperi** [comment] 2017-03-16 09:29
Any news on TurboLinks 5.1?

**Comment by TiuTalk** [comment] 2017-05-23 13:19
@elsurudo can you show us what you did for your Android adapter?

**Comment by elsurudo** [comment] 2017-05-23 17:36
@TiuTalk We created a class that extends `AppCompatActivity` and implements `TurbolinksAdapter`, and in the `public void visitProposedToLocationWithAction(String location, String action)` override, we have (among other things) something like this:

```
if (url.getPath().equals(Application.mProperties.getProperty(Constants.KEY_TURBOLINK_BACK_PATH))){
                    finish();
                } else {
                    Intent intent = new Intent(SimpleTurbolinkActivity.this, SimpleTurbolinkActivity.class);
                    intent.putExtra(EXTRA_WEB_URL, location);
                    startActivity(intent);
                }
```

Very similar to the iOS implementation.

Obviously, this is the activity that needs to be used when showing a Turbolinks page.

**Comment by gregblass** [comment] 2017-11-04 10:51
Any updates on the 5.1 release, or did it get shelved?

**Comment by gregblass** [comment] 2017-11-13 23:33
Hey @sstephenson - No worries either way here - I understand how open source software works, and that people's priorities and time get pulled in other directions - but I was just looking for an honest answer either way as far as the chances of this happening or not?

It looks like you commented in August of '06 that this was planned for release in 5.1, and it's been over a year since then. Any updates on the future of this library or this issue specifically? Any discussion within Basecamp?

If the answer is no, I totally understand - I just want to plan some personal development priorities accordingly.

**Comment by domchristie** [comment] 2018-09-28 11:18
Closing as duplicate of #74

**Closed by domchristie** 2018-09-28 11:18 UTC
