### ISSUE TITLE
How to prevent preview to be Overwrite?

### ISSUE THREAD

**Issue by victorlcampos** [turbolinks/turbolinks#465] opened 2019-04-11 20:07 UTC
Hi Guys,

I have some pages with empty Divs, that the html are loaded by Jquery. All this fields have a loadable class.

I wanted to know how can I use the preview value of this html instead to use the fresh server html (because it's empty).

So when I visit a page that is on cache the turbolinks show to user the div content, so the html content come (empty) from server, then jquery calls ajax to get the fresh content (that in the normaly equals from turbolinks preview).

There is any way to do this?

**Comment by kat0d** [comment] 2019-04-22 08:53
https://github.com/turbolinks/turbolinks#preparing-the-page-to-be-cached

```html
<head>
  ...
  <meta name="turbolinks-cache-control" content="no-cache">
</head>
```

**Comment by domchristie** [comment] 2019-09-17 09:03
Hi @victorlcampos 

If I understand the situation correctly, I think it can be chronicled by:

1. Server-rendered page loads and contains empty `div`s
2. Content is loaded into these `div`s using jQuery
3. User navigates away and Turbolinks takes a snapshot for the cache
4. User returns to the page, and is initially shown the preview from the cache
5. The preview is replaced by the server-rendered page containing empty `div`s
6. Go to Step 2.

and so I suppose the issue is that the content will flash or jump as it transitions from the preview to the server-rendered version, then reloads the `div` content.

There is no straightforward fix for this as it depends on how you're loading and rendering content. You will have to construct your own way to cache the contents of the `div`s and then render that content once the page loads. For example:

```html
<div data-behavior="lazy-load" data-url="/posts/1" id="posts_1"></div>
<div data-behavior="lazy-load" data-url="/posts/2" id="posts_2"></div>
<div data-behavior="lazy-load" data-url="/posts/3" id="posts_2"></div>
```

```js
;(function () {
  // Store for lazily loaded content, referenced by ID
  var lazyLoadCache = {}
  
  $(document).on('turbolinks:load', function () {
    $('[data-behavior="lazy-load"]').each(function (i, el) {
      var $el = $(el)
      
      // Load cached content then remove from cache
      if (lazyLoadCache[el.id]) {
        $el.html(lazyLoadCache[el.id])
        lazyLoadCache[el.id] = null
      }
      
      // Lazily load in content from server
      $.get($el.attr('data-url'), function (html) {
        $el.html(html)
      })
    })
  })
  
  // Cache lazily loaded content
  $(document).on('turbolinks:before-cache', function () {
    $('[data-behavior="lazy-load"]').each(function (i, el) {
      lazyLoadCache[el.id] = $(el).html()
    })
  })
})()
```

This code hasn't been tested, but hopefully you get the idea :)

**Closed** 2019-10-01 07:50 UTC
