### ISSUE TITLE
Add allowLinkExtensions configuration

### ISSUE THREAD

**Issue by candrews** [turbolinks/turbolinks#139] opened 2016-07-11 20:19 UTC
Turbolinks Classic has a configuration option, ``allowLinkExtensions``, which allows additional file extensions to be recognized for opt-in to Turbolinks.

Turbolinks 5 has the rule hardcoded with no way to change it:
https://github.com/turbolinks/turbolinks/blob/55af148d880a3f80654a3a4cde9c8c41dadac861/src/turbolinks/location.coffee#L36

I think that, at least, a mechanism like ``allowLinkExtensions`` should be added. Ideally, a user should be able to provide a function to Turbolinks that accepts a link href and returns a boolean indicating if Turbolinks should handle that href, as that would allow sites don't use file extensions at all to work.

**Comment by sstephenson** [comment] 2016-07-31 15:19
Duplicate of #127 and #15.

**Closed by sstephenson** 2016-07-31 15:19 UTC
