### ISSUE TITLE
Bad behaviour when including Google Maps API

### ISSUE THREAD

**Issue by 2paka** [turbolinks/turbolinks#165] opened 2016-08-11 13:56 UTC
Hi, i'm trying to use Google Maps API in my application with Turbolinks 5 but i have some issues.
Every time i include Google Maps in my application, then, navigating via application visits starts to show some problems, specifically:
pageA has javascript_include_tag "gmaps api" 

Visit pageA -> Visit pageB -> Visit pageC
in pageC i get an error of some libraries that gets undefined, despite of being used previously  and succesfully in pageA and pageB. The chunk of code that breaks is in application.coffee
`document.addEventListener "turbolinks:load", ->
   $.rails.showConfirmDialog = (link) -> [...]
`
ERROR: rails is undefined

The same problem occurs with other libraries. pageB has no javascript. I'm pretty sure that this is because of the inclusion of gmaps. I see the libraries included in the script tags of the head, but, for some reason, there are not being executed.  

Any idea of how can i troubleshoot this?
Thanks.

**Comment by SebastianPoell** [comment] 2016-08-24 01:23
Hey,

I ran into a similar issue today and managed to break it down into a minimal and (hopefully for all) reproducible example. 

```
<%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
<script src="https://maps.googleapis.com/maps/api/js?v=3"></script>
```

When you load the page and open the Inspector/Firebug, you'll notice that GoogleMaps loads some additional script tags into the head. When you then click on a turbolink-link, the first script tag (jQuery in my case), gets duplicated and is suddenly inserted at the bottom of the head section:

![screen shot 2016-08-24 at 03 08 27](https://cloud.githubusercontent.com/assets/1398398/17915109/24eaf34e-69a8-11e6-9ff1-0d2b7c6687d2.png)

Which obviously leads to errors...

My temporary solution to this problem was to just use an empty script tag before all the other scripts get included. This way the empty script tag gets duplicated and everything works.

```
<script></script>
<%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
<script src="https://maps.googleapis.com/maps/api/js?v=3"></script>
```

Important note: This error only occurs in Firefox and Safari. In Chrome everything worked perfectly for me. Turbolinks version is 5.0.1.

Hope that helps ;)
Best Regards

**Comment by teilab** [comment] 2017-05-12 20:58
@SebastianPoell iri (i'm rally impressed). It works! Shouldn't you report this issue somewhere?

**Comment by brandonhilkert** [comment] 2017-09-15 20:12
I had a [similar issue](https://github.com/turbolinks/turbolinks/issues/318) and it was due to Google Maps adding a blank `style=""` tag to the first javascript include on the page. I can see it in your screenshot. 

While this issue is old, just chiming in here in case that info is helpful to others.

**Comment by domchristie** [comment] 2018-09-20 21:04
Resolved by https://github.com/turbolinks/turbolinks/issues/165#issuecomment-241931592 or https://github.com/turbolinks/turbolinks/issues/165#issuecomment-329890062 Thanks!

**Closed by domchristie** 2018-09-20 21:04 UTC
