### ISSUE TITLE
Turbolinks doesn't recognize form re-submission [POST] and navigates instead [GET].

### ISSUE THREAD

**Issue by azeezahmed** [turbolinks/turbolinks#251] opened 2017-03-20 13:28 UTC
**Steps to Reproduce**

1. scaffold a test_app with name: string as a required field.
2. Run migrations.
3. start rails server. [link to test app](https://github.com/azeezahmed/test_app)
4. have the form to generate errors ( name can't be blank )
5. click refresh button (F5).

**Expected Behaviour**

The user should see browser confirm dialog box for form resubmission as below ( POST ).
<img width="499" alt="vvd2i" src="https://cloud.githubusercontent.com/assets/14010276/24101387/2f88ad9c-0d9e-11e7-88d6-fadeca7c9986.png">

**Actual Behaviour**

The page navigates to /users ( users#index, sends GET request).

Removing //= require turbolinks from asset pipeline restores the expected behaviour.
Did not find this issue being reported, please feel free to tag if it's a duplicate of an existing issue.

**Version**

ruby 2.3.3p222
Rails 5.0.2
Turbolinks 5.0.1

**Comment by focused** [comment] 2017-04-20 18:32
similar to #229 and #60

**Comment by kstratis** [comment] 2017-08-15 14:32
I confirm the issue. 
After an invalid submission I always land on `/users/`. To make matters worse on refresh, I have to protect `/users/` otherwise I get `404`.

This should definitely be fixed.

**Comment by 1Mark** [comment] 2017-12-29 00:08
Is there any progress with this?

**Comment by ezr-ondrej** [comment] 2018-08-08 17:44
+1

**Comment by paulodeleo** [comment] 2018-09-19 20:41
+1

**Comment by domchristie** [comment] 2018-09-21 07:16
Closing as duplicate of #60. I have added some more detail explaining the complexity in https://github.com/turbolinks/turbolinks/issues/60#issuecomment-423437233

**Closed by domchristie** 2018-09-21 07:16 UTC
