### ISSUE TITLE
New Turbolinks version?

### ISSUE THREAD

**Issue by nicl** [turbolinks/turbolinks#582] opened 2020-09-25 13:46 UTC
Hi, I've heard that there is a new/updated version of Turbolinks, which was developed for Hey. I was interested in some of the features and wondered if there was a timeline for sharing this?

Thanks.

**Comment by kmmbvnr** [comment] 2020-09-26 07:16
Here is links to couple intriguing dhh  tweets about future plans - https://github.com/turbolinks/turbolinks/issues/576#issuecomment-696166893

**Comment by domchristie** [comment] 2020-09-26 21:03
Closing as duplicate of https://github.com/turbolinks/turbolinks/issues/576

**Closed by domchristie** 2020-09-26 21:03 UTC
Labels: question
